# Generated by Django 5.1.1 on 2025-04-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='emp_id',
            new_name='sallary',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='working',
        ),
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(default=1000, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='emp',
            name='department',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
